import type { Doctor } from "@/lib/types";

/** Fee filter range in CAD (approximate visit pricing). */
export const DOCTOR_FEE_SLIDER_MIN = 90;
export const DOCTOR_FEE_SLIDER_MAX = 450;
export const DOCTOR_FEE_SLIDER_STEP = 10;

/** Canadian cities for search & filters (legacy export name removed — use `canadianCities`). */
export const canadianCities = [
  "Toronto",
  "Vancouver",
  "Montreal",
  "Calgary",
  "Ottawa",
  "Edmonton",
  "Winnipeg",
  "Halifax",
  "Mississauga",
  "Brampton",
  "Hamilton",
  "Quebec City",
  "London",
  "Saskatoon",
  "Victoria",
] as const;

/** Display amounts in Canadian dollars (UI only). */
export function formatCad(amount: number): string {
  return `CA$${amount.toLocaleString("en-CA")}`;
}

export const dentalServices = [
  "Teeth Cleaning",
  "Root Canal",
  "Braces",
  "Teeth Whitening",
  "Extraction",
  "Implants",
  "Veneers",
  "Filling",
  "Crown",
  "Invisalign",
  "Pediatric Dentistry",
  "Smile Design",
] as const;

export const mockDoctors: Doctor[] = [
  {
    id: "dr-1",
    name: "Dr. James Carter",
    specialty: "Dentist",
    services: ["Teeth Cleaning", "Root Canal", "Braces"],
    hospital: "Bright Smile Dental",
    city: "Toronto",
    rating: 4.9,
    reviewCount: 214,
    feeMin: 140,
    feeMax: 320,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 14,
    languages: ["English", "French"],
    gender: "male",
  },
  {
    id: "dr-2",
    name: "Dr. Sarah Mitchell",
    specialty: "Dentist",
    services: ["Teeth Whitening", "Veneers", "Extraction"],
    hospital: "Pacific Dental Care",
    city: "Vancouver",
    rating: 4.8,
    reviewCount: 189,
    feeMin: 130,
    feeMax: 290,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 10,
    languages: ["English"],
    gender: "female",
  },
  {
    id: "dr-3",
    name: "Dr. Michael Brown",
    specialty: "Dentist",
    services: ["Braces", "Invisalign", "Consultation"],
    hospital: "Centre Dentaire Premier",
    city: "Montreal",
    rating: 4.85,
    reviewCount: 302,
    feeMin: 150,
    feeMax: 340,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 16,
    languages: ["English", "French"],
    gender: "male",
  },
  {
    id: "dr-4",
    name: "Dr. Emily Davis",
    specialty: "Dentist",
    services: ["Root Canal", "Crown", "Implants"],
    hospital: "Bow River Family Dental",
    city: "Calgary",
    rating: 4.7,
    reviewCount: 156,
    feeMin: 120,
    feeMax: 280,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 12,
    languages: ["English"],
    gender: "female",
  },
  {
    id: "dr-5",
    name: "Dr. Robert Wilson",
    specialty: "Dentist",
    services: ["Teeth Cleaning", "Filling", "Extraction"],
    hospital: "Rideau Dental Group",
    city: "Ottawa",
    rating: 4.75,
    reviewCount: 278,
    feeMin: 110,
    feeMax: 260,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 9,
    languages: ["English", "French"],
    gender: "male",
  },
  {
    id: "dr-6",
    name: "Dr. Jessica Taylor",
    specialty: "Dentist",
    services: ["Whitening", "Veneers", "Smile Design"],
    hospital: "Square One Smile Studio",
    city: "Mississauga",
    rating: 4.82,
    reviewCount: 131,
    feeMin: 145,
    feeMax: 310,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 11,
    languages: ["English"],
    gender: "female",
  },
  {
    id: "dr-7",
    name: "Dr. David Anderson",
    specialty: "Dentist",
    services: ["Pediatric Dentistry", "Braces", "Cleaning"],
    hospital: "Whyte Avenue Dental",
    city: "Edmonton",
    rating: 4.78,
    reviewCount: 167,
    feeMin: 125,
    feeMax: 270,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 13,
    languages: ["English"],
    gender: "male",
  },
  {
    id: "dr-8",
    name: "Dr. Ashley Thomas",
    specialty: "Dentist",
    services: ["Implants", "Root Canal", "Consultation"],
    hospital: "Harbourfront Dental",
    city: "Halifax",
    rating: 4.76,
    reviewCount: 198,
    feeMin: 135,
    feeMax: 330,
    image: "/images/placeholder-doctor.svg",
    availableToday: true,
    experience: 8,
    languages: ["English"],
    gender: "female",
  },
];
